### ISSUE TITLE
webapp framework for subdomain

### ISSUE THREAD

**Issue by zirdy** [laukstein/ajax-seo#27]
Ajax request doesn't work on subdomain, it's load new full-page on clicked link. is it nedded to set the .htaccess file and/or other config?

**Comment by laukstein** [comment]
Whole ajax-seo [package](https://github.com/laukstein/ajax-seo/archive/master.zip) is required, except **~config** is optional (recommended for full support).

I just tested recent ajax-seo on multiple levels domains and is works fine.
For quickly setup fallow [#quick-start](https://github.com/laukstein/ajax-seo#quick-start), notice also:
> Minimum server requirements Apache 2 + mod_rewrite, MySQL 5, PHP 5.2.
